module.exports.salonValidation = require('./salon.validation')
module.exports.branchValidation = require('./branch.validation')
module.exports.restaurantUserValidation = require('./restaurantuser.validation')
module.exports.serviceValidation = require('./service.validation')
module.exports.categoryValidation = require('./category.validation')
module.exports.hotkeyValidation = require('./hotkey.validation')