module.exports.salonService = require('./salon.service')
module.exports.themeService = require('./theme.service')
module.exports.subscriptionService = require('./subscription.service')
module.exports.categoryTypeService = require('./categorytype.service')
module.exports.expenseTypeService = require('./expensetype.service')
module.exports.assignSubscriptionService = require('./assignsubscription.service')